const true_sentences = [
  ["1T", "An iceberg contains significantly more total heat energy than a burning match."],
  ["2T", "The world's first nuclear reactor was built in a squash court."],
  ["3T", "Adult beavers can hold their breath for up to 15 minutes under water."],
  ["4T", "A bee has 5 eyes."],
  ["5T", "A honeybee can fly at 15 mph."],
  ["6T", "Studies suggest that ants can lift up to 5000 times their own weight."],
  ["7T", "Camel's milk does not curdle."],
  ["8T", "The average ruby-throated hummingbird weighs less than a nickel."],
  ["9T", "Almonds are part of the peach family."],
  ["10T", "No only child has ever been a U.S. president."],
  ["11T", "In the late 1800s, the United States Mint issued 2-cent and 3-cent coins."],
  ["12T", "The starfish is the only animal that can turn its stomach inside out."],
  ["13T", "If you keep a goldfish in a dark room, it will eventually turn white."],
  ["14T", "Texas is the only state that permits residents to cast absentee ballots from space."],
  ["15T", "The speed limit in New York City was nine mph in 1895."],
  ["16T", "A male kangaroo is called a boomer."],
  ["17T", "Louisiana was named after Louis 14th."],
  ["18T", "The mouth of the Statue of Liberty is 3 feet wide."],
  ["19T", "Giraffes can lick their own eyes."],
  ["20T", "There are towns named Sandwich in Illinois and Massachusetts."],
  ["21T", "Half your body's red blood cells are replaced every seven days."],
  ["22T", "Blood makes up about 7% of your body's weight."],
  ["23T", "There is a type of catfish that can walk on land."],
  ["24T", "A starfish can release approximately 2.5 million eggs at once."],
  ["25T", "Jellyfish do not have hearts."],
  ["26T", "Traffic lights were invented before automobiles."],
  ["27T", "Tennis was invented before golf."],
  ["28T", "Dishwashers were invented before washing machines."],
  ["29T", "Montpelier, Vermont is the only U.S. state capital without a McDonalds."],
  ["30T", "Rhode Island never ratified the 18th Amendment."],
  ["31T", "Oregon's state birthday is on Valentine's Day."],
  ["32T", "Camels have three eyelids on each eye."],
  ["33T", "Venus rotates clockwise."],
  ["34T", "A group of crows is called a murder."],
  ["35T", "Nepal is the only country whose national flag is not rectangular."],
  ["36T", "France's land area is smaller than Colombia's."],
  ["37T", "The United States has no official language."],
  ["38T", "An ostrich's eye is larger than its brain."],
  ["39T", "Jimmy Carter was the first U.S. president born in a hospital."],
  ["40T", "James Madison was the shortest U.S. president."],
  ["41T", "Three U.S. presidents have been awarded honorary knighthood."],
  ["42T", "Chameleons' tongues can stretch to two times their body length."],
  ["43T", "The cheetah is the only cat that cannot retract its claws."],
  ["44T", "The large intestine is about 5 feet long."],
  ["45T", "The first trains went into operation in the 1700s."],
  ["46T", "Roughly 3% of the world's water is fresh water."],
  ["47T", "Tapeworms can reach up to 98 feet in length."],
  ["48T", "The center of a star can be over 50 million degrees Fahrenheit."],
  ["49T", "The U.S. was the first country to use a submarine in warfare."],
  ["50T", "Only female mosquitoes bite."],
  ["51T", "A shrimp's heart is located in its head."],
  ["52T", "Jupiter's mass is approximately 317 times earth's."]
];

const false_sentences = [
  ["1F", "An iceberg contains significantly less total heat energy than a burning match."],
  ["2F", "The world's first nuclear reactor was built in a tennis court."],
  ["3F", "Adult beavers can hold their breath for up to 45 minutes under water."],
  ["4F", "A bee has 3 eyes."],
  ["5F", "A honeybee can fly at 35 mph."],
  ["6F", "Studies suggest that ants can lift up to 50,000 times their own weight."],
  ["7F", "Camel's milk curdles faster than cow's milk."],
  ["8F", "The average ruby-throated hummingbird has the same weight as 3 nickels."],
  ["9F", "Almonds are part of the apple family."],
  ["10F", "Fourteen U.S. presidents have been only children."],
  ["11F", "In the late 1900s, the United States Mint issued 2-cent and 3-cent coins."],
  ["12F", "The clownfish is the only animal that can turn its stomach inside out."],
  ["13F", "If you keep a goldfish in a dark room, it will eventually turn black."],
  ["14F", "Alabama is the only state that permits residents to cast absentee ballots from space."],
  ["15F", "The speed limit in New York City was fifteen mph in 1895."],
  ["16F", "A female kangaroo is called a boomer."],
  ["17F", "Louisiana was named after Louis 16th."],
  ["18F", "The mouth of the Statue of Liberty is 7 feet wide."],
  ["19F", "Kangaroos can lick their own eyes."],
  ["20F", "There are towns named Sandwich in Arizona and Massachusetts."],
  ["21F", "Half your body's red blood cells are replaced every three days."],
  ["22F", "Blood makes up about 11% of your body's weight."],
  ["23F", "There are no species of fish which can walk on land."],
  ["24F", "A starfish can release approximately 5 million eggs at once."],
  ["25F", "Jellyfish have two hearts."],
  ["26F", "Automobiles were invented before traffic lights."],
  ["27F", "Golf was invented before tennis."],
  ["28F", "Washing Machines were invented before dishwashers."],
  ["29F", "Harrisburg, Pennsylvania is the only U.S. state capital without a McDonalds."],
  ["30F", "Delaware never ratified the 18th Amendment."],
  ["31F", "Mississippi's state birthday is on Valentine's Day."],
  ["32F", "Camels have four eyelids on each eye."],
  ["33F", "Venus rotates counter-clockwise."],
  ["34F", "A group of crows is called a crew."],
  ["35F", "Taiwan is the only country whose national flag is not rectangular."],
  ["36F", "France has twice the land area of Colombia."],
  ["37F", "English is the official language of the United States."],
  ["38F", "An ostrich's eye is half the size of its brain."],
  ["39F", "Gerald Ford was the first U.S. president born in a hospital."],
  ["40F", "James Monroe was the shortest U.S. president."],
  ["41F", "Four U.S. presidents have been awarded honorary knighthood."],
  ["42F", "Chameleons' tongues can stretch to four times their body length."],
  ["43F", "The jaguar is the only cat that cannot retract its claws."],
  ["44F", "The large intestine is about 7 feet long."],
  ["45F", "The first trains went into operation in the 1690s."],
  ["46F", "Roughly 7% of the world's water is fresh water."],
  ["47F", "Tapeworms can reach up to 200 feet in length."],
  ["48F", "The center of a star can be over 75 million degrees Fahrenheit."],
  ["49F", "Germany was the first country to use a submarine in warfare."],
  ["50F", "Only male mosquitoes bite."],
  ["51F", "A shrimp's heart is located in its abdomen."],
  ["52F", "Jupiter's mass is more than 400 times that of the earth."]
];

let trial_objects = [
  ...true_sentences.map(([code, stimulus]) => ({
    code,
    stimulus,
    condition: "true"
  })),
  ...false_sentences.map(([code, stimulus]) => ({
    code,
    stimulus,
    condition: "false"
  }))
];
