const true_sentences = [
  ["1T", "An iceberg contains significantly more total heat energy than a burning match."],
  ["2T", "The world's first nuclear reactor was built in a squash court."],
  ["3T", "Animals that lay eggs don't have belly buttons."],
  ["4T", "Adult beavers can hold their breath for up to 15 minutes under water."],
  ["5T", "A bee has 5 eyes."],
  ["6T", "A honeybee can fly at 15 mph."],
  ["7T", "Studies suggest that ants can lift up to 5000 times their own weight."],
  ["8T", "Camel's milk does not curdle."],
  ["9T", "The average ruby-throated hummingbird weighs less than a nickel."],
  ["10T", "Almonds are part of the peach family."],
  ["11T", "A ball of glass will bounce higher than a ball of rubber."],
  ["12T", "Elephants can't jump."],
  ["13T", "No only child has ever been a U.S. president."],
  ["14T", "In the late 1800s, the United States Mint issued 2-cent and 3-cent coins."],
  ["15T", "The starfish is the only animal that can turn its stomach inside out."],
  ["16T", "If you keep a goldfish in a dark room, it will eventually turn white."],
  ["17T", "A seal can sleep while three-quarters of its brain remains awake."],
  ["18T", "A crocodile can stick its tongue out further than any other animal."],
  ["19T", "China only has one official time zone."],
  ["20T", "Texas is the only state that permits residents to cast absentee ballots from space."],
  ["21T", "The speed limit in New York City was nine mph in 1895."],
  ["22T", "Before mercury, brandy was used to fill thermometers."],
  ["23T", "A male kangaroo is called a boomer."],
  ["24T", "Louisiana was named after Louis 14th."],
  ["25T", "The mouth of the Statue of Liberty is 3 feet wide."],
  ["26T", "Giraffes can lick their own eyes."],
  ["27T", "There are towns named Sandwich in Illinois and Massachusetts."],
  ["28T", "Cows give more milk when they listen to music."],
  ["29T", "The state of Arizona does not observe daylight savings time."],
  ["30T", "Half your body's red blood cells are replaced every seven days."],
  ["31T", "Blood makes up about 7% of your body's weight."],
  ["32T", "There is a type of catfish that can walk on land."],
  ["33T", "A jellyfish is more than 95% water."],
  ["34T", "A starfish can release approximately 2.5 million eggs at once."],
  ["35T", "Jellyfish do not have hearts."],
  ["36T", "Traffic lights were invented before automobiles."],
  ["37T", "Your heart does not momentarily stop when you sneeze."],
  ["38T", "Tennis was invented before golf."],
  ["39T", "Dishwashers were invented before washing machines."],
  ["40T", "In colonial times, only slaves ate lobster."],
  ["41T", "Montpelier, Vermont is the only U.S. state capital without a McDonalds."],
  ["42T", "Rhode Island never ratified the 18th Amendment (Prohibition)."],
  ["43T", "Oregon's state birthday is on Valentine's Day."],
  ["44T", "Camels have three eyelids on each eye."],
  ["45T", "Children tend to grow faster in the spring."],
  ["46T", "Venus rotates clockwise."],
  ["47T", "A group of crows is called a murder."],
  ["48T", "Nepal is the only country whose national flag is not rectangular."],
  ["49T", "Owls can see the color blue."],
  ["50T", "France's land area is smaller than Colombia's."],
  ["51T", "English is the official language of the United States."],
  ["52T", "An ostrich's eye is larger than its brain."],
  ["53T", "Jimmy Carter was the first U.S. president born in a hospital."],
  ["54T", "James Madison was the shortest U.S. president."],
  ["55T", "Three U.S. presidents have been awarded honorary knighthood."],
  ["56T", "Chameleons' tongues can stretch to two times their body length."],
  ["57T", "The cheetah is the only cat that cannot retract its claws."],
  ["58T", "The large intestine is about 5 feet long."],
  ["59T", "The first trains went into operation in the 1700s."],
  ["60T", "The first VCR was made in 1969."],
  ["61T", "Roughly 3% of the world's water is fresh water."],
  ["62T", "In Ancient Egypt, a yard was the length of a man's arm from nose to tip."],
  ["63T", "The blue whale is the largest animal that has ever lived on earth."],
  ["64T", "Tapeworms can reach up to 98 feet in length."],
  ["65T", "The center of a star can be over 50 million degrees Fahrenheit."],
  ["66T", "The U.S. was the first country to use a submarine in warfare."],
  ["67T", "Only female mosquitoes bite."],
  ["68T", "Coca Cola is only brown because of food coloring."],
  ["69T", "A shrimp's heart is located in its head."],
  ["70T", "Honduras currently has the highest murder rate of any country in the world."],
  ["71T", "Women blink more frequently than do men."],
  ["72T", "Jupiter's mass is approximately 317 times earth's."]
];

const false_sentences = [
  ["1F", "An iceberg contains significantly less total heat energy than a burning match."],
  ["2F", "The world's first nuclear reactor was built in a tennis court."],
  ["3F", "Some animals that lay eggs have belly buttons."],
  ["4F", "Adult beavers can hold their breath for up to 45 minutes under water."],
  ["5F", "A bee has 3 eyes."],
  ["6F", "A honeybee can fly at 35 mph."],
  ["7F", "Studies suggest that ants can lift up to 50,000 times their own weight."],
  ["8F", "Camel's milk curdles faster than cow's milk."],
  ["9F", "The average ruby-throated hummingbird has the same weight as 3 nickels."],
  ["10F", "Almonds are part of the apple family."],
  ["11F", "A ball of rubber will bounce higher than a ball of glass."],
  ["12F", "Elephants can jump higher than humans."],
  ["13F", "Fourteen U.S. presidents have been only children."],
  ["14F", "In the late 1900s, the United States Mint issued 2-cent and 3-cent coins."],
  ["15F", "The clownfish is the only animal that can turn its stomach inside out."],
  ["16F", "If you keep a goldfish in a dark room, it will eventually turn black."],
  ["17F", "A seal can sleep while three-quarters of its brain remains awake."],
  ["18F", "A crocodile cannot stick out its tongue."],
  ["19F", "China has five official time zones."],
  ["20F", "Alabama is the only state that permits residents to cast absentee ballots from space."],
  ["21F", "The speed limit in New York City was fifteen mph in 1895."],
  ["22F", "Before mercury, whisky was used to fill thermometers."],
  ["23F", "A female kangaroo is called a boomer."],
  ["24F", "Louisiana was named after Louis 16th."],
  ["25F", "The mouth of the Statue of Liberty is 7 feet wide."],
  ["26F", "Kangaroos can lick their own eyes."],
  ["27F", "There are towns named Sandwich in Arizona and Massachusetts."],
  ["28F", "Cows give more milk when milked in complete silence."],
  ["29F", "The state of Montana does not observe daylight savings time."],
  ["30F", "Half your body's red blood cells are replaced every three days."],
  ["31F", "Blood makes up about 11% of your body's weight."],
  ["32F", "There are no species of fish which can walk on land."],
  ["33F", "A jellyfish is more than 70% water."],
  ["34F", "A starfish can release approximately 5 million eggs at once."],
  ["35F", "Jellyfish have two hearts."],
  ["36F", "Automobiles were invented before traffic lights."],
  ["37F", "Your heart stops momentarily when you sneeze."],
  ["38F", "Golf was invented before tennis."],
  ["39F", "Washing machines were invented before dishwashers."],
  ["40F", "In colonial times, only the elite classes ate lobster."],
  ["41F", "Harrisburg, Pennsylvania is the only U.S. state capital without a McDonalds."],
  ["42F", "Delaware never ratified the 18th Amendment (Prohibition)."],
  ["43F", "Mississippi's state birthday is on Valentine's Day."],
  ["44F", "Camels have four eyelids on each eye."],
  ["45F", "Children tend to grow faster in the winter."],
  ["46F", "Venus rotates counter-clockwise."],
  ["47F", "A group of crows is called a crew."],
  ["48F", "Taiwan is the only country whose national flag is not rectangular."],
  ["49F", "Owls cannot see the color blue."],
  ["50F", "France has twice the land area of Colombia."],
  ["51F", "The United States has no official language."],
  ["52F", "An ostrich's eye is half the size of its brain."],
  ["53F", "Gerald Ford was the first U.S. president born in a hospital."],
  ["54F", "James Monroe was the shortest U.S. president."],
  ["55F", "Four U.S. presidents have been awarded honorary knighthood."],
  ["56F", "Chameleons' tongues can stretch to four times their body length."],
  ["57F", "The jaguar is the only cat that cannot retract its claws."],
  ["58F", "The large intestine is about 7 feet long."],
  ["59F", "The first trains went into operation in the 1690s."],
  ["60F", "The first VCR was made in 1973."],
  ["61F", "Roughly 7% of the world's water is fresh water."],
  ["62F", "In Ancient Egypt, a yard was the length of a man's arm span."],
  ["63F", "The blue whale is the second largest animal that has ever lived on earth."],
  ["64F", "Tapeworms can reach up to 200 feet in length."],
  ["65F", "The center of a star can be over 75 million degrees Fahrenheit."],
  ["66F", "Germany was the first country to use a submarine in warfare."],
  ["67F", "Only male mosquitoes bite."],
  ["68F", "Coca Cola would be green without the added food coloring."],
  ["69F", "A shrimp's heart is located in its abdomen."],
  ["70F", "Venezuela currently has the highest murder rate of any country in the world."],
  ["71F", "Men blink more frequently than do women."],
  ["72F", "Jupiter's mass is more than 400 times that of the earth."]
];

let trial_objects = [
  ...true_sentences.map(([code, stimulus]) => ({
    code,
    stimulus,
    condition: "true"
  })),
  ...false_sentences.map(([code, stimulus]) => ({
    code,
    stimulus,
    condition: "false"
  }))
];
